// <auto-generated />
using System;
using Daycare.Domain.Repositories.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Daycare.WebAPIHost.Migrations.AppDb
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Daycare.Domain.Entities.Daycare.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ActivityId"));

                    b.Property<string>("ActivityDescription")
                        .HasColumnType("text");

                    b.Property<string>("ActivityName")
                        .HasColumnType("text");

                    b.Property<string>("ChildFirstName")
                        .HasColumnType("text");

                    b.Property<int?>("ChildId")
                        .HasColumnType("integer");

                    b.Property<string>("ChildLastName")
                        .HasColumnType("text");

                    b.Property<string>("ChildMiddleName")
                        .HasColumnType("text");

                    b.Property<string>("ChildMyoji")
                        .HasColumnType("text");

                    b.Property<string>("ChildShimei")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<string>("Parent1Id")
                        .HasColumnType("text");

                    b.Property<string>("Parent2Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ActivityId");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("Daycare.Domain.Entities.Daycare.AttendanceRecord", b =>
                {
                    b.Property<int>("AttendanceRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AttendanceRecordId"));

                    b.Property<bool?>("Absent")
                        .HasColumnType("boolean");

                    b.Property<string>("AbsentComment")
                        .HasColumnType("text");

                    b.Property<string>("Absent_EnteredBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Absent_StampTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CancelInTime_EnteredBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CancelInTime_StampTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CancelOutTime_EnteredBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CancelOutTime_StampTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ChildFirstName")
                        .HasColumnType("text");

                    b.Property<int?>("ChildId")
                        .HasColumnType("integer");

                    b.Property<string>("ChildLastName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<DateTime?>("InTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("InTime_EnteredBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("InTime_StampTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("LeaveEarly")
                        .HasColumnType("boolean");

                    b.Property<string>("LeaveEarlyComment")
                        .HasColumnType("text");

                    b.Property<string>("LeaveEarly_EnteredBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LeaveEarly_StampTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("OutTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OutTime_EnteredBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("OutTime_StampTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Parent1Id")
                        .HasColumnType("text");

                    b.Property<string>("Parent2Id")
                        .HasColumnType("text");

                    b.Property<bool?>("Tardy")
                        .HasColumnType("boolean");

                    b.Property<string>("TardyComment")
                        .HasColumnType("text");

                    b.Property<string>("Tardy_EnteredBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Tardy_StampTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("AttendanceRecordId");

                    b.ToTable("AttendanceRecord");
                });

            modelBuilder.Entity("Daycare.Domain.Entities.Daycare.Chat.ChatMessage", b =>
                {
                    b.Property<int>("ChatMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChatMessageId"));

                    b.Property<string>("ChatWithUserFirstName")
                        .HasColumnType("text");

                    b.Property<string>("ChatWithUserId")
                        .HasColumnType("text");

                    b.Property<string>("ChatWithUserLastName")
                        .HasColumnType("text");

                    b.Property<string>("ChatWithUserType")
                        .HasColumnType("text");

                    b.Property<string>("ChildFirstName")
                        .HasColumnType("text");

                    b.Property<int?>("ChildId")
                        .HasColumnType("integer");

                    b.Property<string>("ChildLastName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("LoginUserFirstName")
                        .HasColumnType("text");

                    b.Property<string>("LoginUserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginUserLastName")
                        .HasColumnType("text");

                    b.Property<string>("LoginUserType")
                        .HasColumnType("text");

                    b.Property<string>("MessageContent")
                        .HasColumnType("text");

                    b.Property<string>("MessageType")
                        .HasColumnType("text");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer");

                    b.HasKey("ChatMessageId");

                    b.ToTable("ChatMessage");
                });

            modelBuilder.Entity("Daycare.Domain.Entities.Daycare.Chat.ChatUser", b =>
                {
                    b.Property<int>("ChatUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChatUserId"));

                    b.Property<string>("ChatWithUserFirstName")
                        .HasColumnType("text");

                    b.Property<string>("ChatWithUserId")
                        .HasColumnType("text");

                    b.Property<string>("ChatWithUserLastName")
                        .HasColumnType("text");

                    b.Property<string>("ChatWithUserType")
                        .HasColumnType("text");

                    b.Property<string>("ChildFirstName")
                        .HasColumnType("text");

                    b.Property<int?>("ChildId")
                        .HasColumnType("integer");

                    b.Property<string>("ChildLastName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("LastMessageText")
                        .HasColumnType("text");

                    b.Property<string>("LoginUserFirstName")
                        .HasColumnType("text");

                    b.Property<string>("LoginUserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginUserLastName")
                        .HasColumnType("text");

                    b.Property<string>("LoginUserType")
                        .HasColumnType("text");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer");

                    b.HasKey("ChatUserId");

                    b.ToTable("ChatUser");
                });

            modelBuilder.Entity("Daycare.Domain.Entities.Daycare.Child", b =>
                {
                    b.Property<int>("ChildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChildId"));

                    b.Property<bool?>("ActiveStatus")
                        .HasColumnType("boolean");

                    b.Property<bool?>("AttendFri")
                        .HasColumnType("boolean");

                    b.Property<bool?>("AttendMon")
                        .HasColumnType("boolean");

                    b.Property<bool?>("AttendSat")
                        .HasColumnType("boolean");

                    b.Property<bool?>("AttendSun")
                        .HasColumnType("boolean");

                    b.Property<bool?>("AttendThu")
                        .HasColumnType("boolean");

                    b.Property<bool?>("AttendTue")
                        .HasColumnType("boolean");

                    b.Property<bool?>("AttendWed")
                        .HasColumnType("boolean");

                    b.Property<string>("ChildFirstName")
                        .HasColumnType("text");

                    b.Property<string>("ChildLastName")
                        .HasColumnType("text");

                    b.Property<string>("ChildMiddleName")
                        .HasColumnType("text");

                    b.Property<string>("ChildMyoji")
                        .HasColumnType("text");

                    b.Property<string>("ChildShimei")
                        .HasColumnType("text");

                    b.Property<string>("ClassName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<int?>("Grade")
                        .HasColumnType("integer");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<string>("Parent1Id")
                        .HasColumnType("text");

                    b.Property<string>("Parent2Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RegisteredDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ChildId");

                    b.ToTable("Child");
                });

            modelBuilder.Entity("Daycare.Domain.Entities.Daycare.CommentRecord", b =>
                {
                    b.Property<int>("CommentRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommentRecordId"));

                    b.Property<bool?>("Absence")
                        .HasColumnType("boolean");

                    b.Property<string>("ChildFirstName")
                        .HasColumnType("text");

                    b.Property<int?>("ChildId")
                        .HasColumnType("integer");

                    b.Property<string>("ChildLastName")
                        .HasColumnType("text");

                    b.Property<string>("Comment1")
                        .HasColumnType("text");

                    b.Property<string>("Comment2")
                        .HasColumnType("text");

                    b.Property<string>("Comment3")
                        .HasColumnType("text");

                    b.Property<string>("Memo1")
                        .HasColumnType("text");

                    b.Property<string>("Memo2")
                        .HasColumnType("text");

                    b.Property<string>("Memo3")
                        .HasColumnType("text");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<bool?>("Others")
                        .HasColumnType("boolean");

                    b.Property<string>("Parent1Id")
                        .HasColumnType("text");

                    b.Property<string>("Parent2Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RecordedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("Tardy")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("CommentRecordId");

                    b.ToTable("CommentRecord");
                });

            modelBuilder.Entity("Daycare.Domain.Entities.Daycare.DeviceToken", b =>
                {
                    b.Property<int>("DeviceTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeviceTokenId"));

                    b.Property<string>("Platform")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("DeviceTokenId");

                    b.ToTable("DeviceToken");
                });

            modelBuilder.Entity("Daycare.Domain.Entities.Daycare.GrowthRecord", b =>
                {
                    b.Property<int>("GrowthRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GrowthRecordId"));

                    b.Property<string>("ChildFirstName")
                        .HasColumnType("text");

                    b.Property<int?>("ChildId")
                        .HasColumnType("integer");

                    b.Property<string>("ChildLastName")
                        .HasColumnType("text");

                    b.Property<double?>("HeightCM")
                        .HasColumnType("double precision");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<string>("Parent1Id")
                        .HasColumnType("text");

                    b.Property<string>("Parent2Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RecordDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("WeightKG")
                        .HasColumnType("double precision");

                    b.HasKey("GrowthRecordId");

                    b.ToTable("GrowthRecord");
                });

            modelBuilder.Entity("Daycare.Domain.Entities.Daycare.MealRecord", b =>
                {
                    b.Property<int?>("MealRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("MealRecordId"));

                    b.Property<bool?>("AMSnack")
                        .HasColumnType("boolean");

                    b.Property<string>("AMSnackCreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AMSnackCreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("AMSnackDescription")
                        .HasColumnType("text");

                    b.Property<string>("AMSnackQuantity")
                        .HasColumnType("text");

                    b.Property<bool?>("AMSnackVisibleToStaffOnly")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Breakfast")
                        .HasColumnType("boolean");

                    b.Property<string>("BreakfastCreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BreakfastCreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("BreakfastDescription")
                        .HasColumnType("text");

                    b.Property<string>("BreakfastQuantity")
                        .HasColumnType("text");

                    b.Property<bool?>("BreakfastVisibleToStaffOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("ChildFirstName")
                        .HasColumnType("text");

                    b.Property<int?>("ChildId")
                        .HasColumnType("integer");

                    b.Property<string>("ChildLastName")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool?>("Dinner")
                        .HasColumnType("boolean");

                    b.Property<string>("DinnerCreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DinnerCreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DinnerDescription")
                        .HasColumnType("text");

                    b.Property<string>("DinnerQuantity")
                        .HasColumnType("text");

                    b.Property<bool?>("DinnerVisibleToStaffOnly")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("EndStampTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<bool?>("LateSnack")
                        .HasColumnType("boolean");

                    b.Property<string>("LateSnackCreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LateSnackCreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LateSnackDescription")
                        .HasColumnType("text");

                    b.Property<string>("LateSnackQuantity")
                        .HasColumnType("text");

                    b.Property<bool?>("LateSnackVisibleToStaffOnly")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Lunch")
                        .HasColumnType("boolean");

                    b.Property<string>("LunchCreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LunchCreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LunchDescription")
                        .HasColumnType("text");

                    b.Property<string>("LunchQuantity")
                        .HasColumnType("text");

                    b.Property<bool?>("LunchVisibleToStaffOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("MealType")
                        .HasColumnType("text");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<bool?>("PMSnack")
                        .HasColumnType("boolean");

                    b.Property<string>("PMSnackCreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PMSnackCreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PMSnackDescription")
                        .HasColumnType("text");

                    b.Property<string>("PMSnackQuantity")
                        .HasColumnType("text");

                    b.Property<bool?>("PMSnackVisibleToStaffOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("Parent1Id")
                        .HasColumnType("text");

                    b.Property<string>("Parent2Id")
                        .HasColumnType("text");

                    b.Property<string>("Quantity")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("VisibleToStaffOnly")
                        .HasColumnType("boolean");

                    b.HasKey("MealRecordId");

                    b.ToTable("MealRecord");
                });

            modelBuilder.Entity("Daycare.Domain.Entities.Daycare.NapRecord", b =>
                {
                    b.Property<int>("NapRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NapRecordId"));

                    b.Property<string>("ChildFirstName")
                        .HasColumnType("text");

                    b.Property<int?>("ChildId")
                        .HasColumnType("integer");

                    b.Property<string>("ChildLastName")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndStampTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FirstCreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FirstCreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FirstDescription")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FirstEndStampTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FirstStartStampTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("FirstVisibleToStaffOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("NapType")
                        .HasColumnType("text");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<string>("Parent1Id")
                        .HasColumnType("text");

                    b.Property<string>("Parent2Id")
                        .HasColumnType("text");

                    b.Property<string>("SecondCreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SecondCreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SecondDescription")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SecondEndStampTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("SecondStartStampTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("SecondVisibleToStaffOnly")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("StartStampTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ThirdCreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ThirdCreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ThirdDescription")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ThirdEndStampTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ThirdStartStampTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("ThirdVisibleToStaffOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("VisibleToStaffOnly")
                        .HasColumnType("boolean");

                    b.HasKey("NapRecordId");

                    b.ToTable("NapRecord");
                });

            modelBuilder.Entity("Daycare.Domain.Entities.Daycare.Organization", b =>
                {
                    b.Property<int>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrganizationId"));

                    b.Property<string>("Apartment_Etc")
                        .HasColumnType("text");

                    b.Property<string>("Cho_Son")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text");

                    b.Property<string>("ContactTelNo")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("NumberOfChildGroup")
                        .HasColumnType("text");

                    b.Property<string>("OrganiationCode")
                        .HasColumnType("text");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("text");

                    b.Property<string>("OrganizationType")
                        .HasColumnType("text");

                    b.Property<string>("OwnerName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RegisteredDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Shi_Gun_Ku")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.Property<string>("Street2")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("To_Do_Fu_Ken")
                        .HasColumnType("text");

                    b.Property<string>("Yubin_Bango")
                        .HasColumnType("text");

                    b.Property<string>("Zip")
                        .HasColumnType("text");

                    b.HasKey("OrganizationId");

                    b.ToTable("Organization");
                });

            modelBuilder.Entity("Daycare.Domain.Entities.Daycare.Photo", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PhotoId"));

                    b.Property<bool?>("ActiveStatus")
                        .HasColumnType("boolean");

                    b.Property<string>("BlobName")
                        .HasColumnType("text");

                    b.Property<string>("Caption")
                        .HasColumnType("text");

                    b.Property<int?>("ChildId")
                        .HasColumnType("integer");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("text");

                    b.HasKey("PhotoId");

                    b.ToTable("Photo");
                });

            modelBuilder.Entity("Daycare.Domain.Entities.Daycare.PottyRecord", b =>
                {
                    b.Property<int>("PottyRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PottyRecordId"));

                    b.Property<string>("ChildFirstName")
                        .HasColumnType("text");

                    b.Property<int?>("ChildId")
                        .HasColumnType("integer");

                    b.Property<string>("ChildLastName")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FifthCreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FifthCreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FifthDescription")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FifthStampTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("FifthVisibleToStaffOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstCreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FirstCreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FirstDescription")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FirstStampTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("FirstVisibleToStaffOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("ForthCreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ForthCreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ForthDescription")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ForthStampTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("ForthVisibleToStaffOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<string>("Parent1Id")
                        .HasColumnType("text");

                    b.Property<string>("Parent2Id")
                        .HasColumnType("text");

                    b.Property<string>("PottyType")
                        .HasColumnType("text");

                    b.Property<string>("SecondCreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SecondCreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SecondDescription")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SecondStampTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("SecondVisibleToStaffOnly")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("StampTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ThirdCreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ThirdCreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ThirdDescription")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ThirdStampTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("ThirdVisibleToStaffOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("VisibleToStaffOnly")
                        .HasColumnType("boolean");

                    b.HasKey("PottyRecordId");

                    b.ToTable("PottyRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
